[package]
name = "lab01_source"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
byteorder = "1.4.3"
bitvec = "1.0.1"
